# Note spring.jpa.database must contain upper case value per org.springframework.com.jpa.vendor.Database
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/sfg_dev?useSSL=false&serverTimezone=UTC
        username: sfg_dev_user
        password: guru

    jpa:
        hibernate:
            ddl-auto: create-drop
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        properties:
            hibernate:
                hbm2ddl:
                    delimiter: ";"            javax:
                persistence:
                    schema-generation:
                        scripts:
                            action: create
                            create-target: database_create.sql
                            create-source: metadata
