# Note spring.jpa.database must contain upper case value per org.springframework.com.jpa.vendor.Database
# spring.jpa.hibernate.ddl-auto can be create, create-drop, none, update, or validate.
# spring.jpa.properties.javax.persistence.schema-generation.scripts.action can be none, create, drop, drop-and-create
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/sfg_dev?useSSL=false&serverTimezone=UTC
        username: sfg_dev_user
        password: guru
        platform: mysql

    jpa:
        hibernate:
            ddl-auto:  validate
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        properties:
            hibernate:
                hbm2ddl:
                    delimiter: ";"

            javax:
                persistence:
                    schema-generation:
                        scripts:
                            action: none
                            create-target: database_create.sql
                            create-source: metadata
